import nodemailer from 'nodemailer';

let transporter = null;

function getTransporter() {
  if (!transporter) {
    const user = process.env.GMAIL_USER;
    const pass = process.env.GMAIL_APP_PASSWORD;

    if (!user || !pass) {
      console.warn('Warning: Gmail credentials not set, skipping email.');
      return null;
    }

    transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: { user, pass },
    });
  }
  return transporter;
}

export async function sendArticleEmail(article) {
  const t = getTransporter();
  if (!t) return;

  const to = process.env.NOTIFICATION_EMAIL;
  if (!to) return;

  // Read the frontmatter for metadata
  const titleMatch = article.content.match(/^title:\s*"?([^"\n]+)"?/m);
  const title = titleMatch ? titleMatch[1] : 'New Article';

  // Convert markdown content to simple HTML for the email
  let body = article.content;

  // Remove frontmatter
  const frontmatterEnd = body.indexOf('---', 3);
  if (frontmatterEnd !== -1) {
    body = body.slice(frontmatterEnd + 3).trim();
  }

  // Convert tweet embeds to clickable links for email
  body = body.replace(
    /<blockquote class="twitter-tweet"><a href="([^"]+)"><\/a><\/blockquote>/g,
    '<div style="background:#f0f9ff;border-left:4px solid #1da1f2;padding:12px 16px;margin:16px 0;border-radius:4px;">📌 <strong>Official announcement on X:</strong><br><a href="$1" style="color:#1da1f2;">View the full post on X →</a></div>'
  );

  // Convert markdown to HTML
  body = body
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    .split('\n\n')
    .map((block) => {
      block = block.trim();
      if (!block) return '';
      if (block.startsWith('<h') || block.startsWith('<blockquote')) return block;
      return '<p>' + block + '</p>';
    })
    .filter((b) => b)
    .join('\n');

  // Extract frontmatter metadata for the email header
  const metaMatch = article.content.match(/metaDescription:\s*"?([^"\n]+)"?/m);
  const slugMatch = article.content.match(/slug:\s*"?([^"\n]+)"?/m);
  const imageMatch = article.content.match(/imageUrl:\s*"?([^"\n]+)"?/m);

  const metaDesc = metaMatch ? metaMatch[1] : '';
  const slug = slugMatch ? slugMatch[1] : '';
  const imageUrl = imageMatch ? imageMatch[1] : '';

  const htmlEmail = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Georgia, serif; max-width: 700px; margin: 0 auto; padding: 20px; color: #333; }
    h1 { font-size: 28px; line-height: 1.3; margin-bottom: 8px; }
    h2 { font-size: 22px; margin-top: 24px; }
    h3 { font-size: 18px; margin-top: 20px; }
    p { font-size: 16px; line-height: 1.7; }
    a { color: #1a73e8; }
    .meta { background: #f5f5f5; padding: 16px; border-radius: 8px; margin-bottom: 24px; font-size: 14px; }
    .meta strong { display: block; margin-bottom: 4px; }
    .divider { border-top: 1px solid #ddd; margin: 24px 0; }
    .footer { font-size: 12px; color: #888; }
    blockquote { border-left: 3px solid #1da1f2; padding-left: 12px; margin: 16px 0; }
    ${imageUrl ? 'img.hero { width: 100%; border-radius: 8px; margin-bottom: 20px; }' : ''}
  </style>
</head>
<body>
  <div class="meta">
    <strong>New article ready for review</strong>
    Title: ${title}<br>
    ${metaDesc ? `Description: ${metaDesc}<br>` : ''}
    ${slug ? `Suggested slug: /blogs/${slug}<br>` : ''}
    Sources: ${article.sources || 'N/A'}
  </div>

  ${imageUrl ? `<img class="hero" src="${imageUrl}" alt="${title}">` : ''}

  <h1>${title}</h1>

  ${body}

  <div class="divider"></div>
  <div class="footer">
    Generated by Content Pipeline<br>
    Review this article and upload it to the admin panel if approved.
  </div>
</body>
</html>`;

  // Build raw HTML for admin panel paste (keeps tweet embeds intact)
  let adminBody = article.content;
  const adminFrontmatterEnd = adminBody.indexOf('---', 3);
  if (adminFrontmatterEnd !== -1) {
    adminBody = adminBody.slice(adminFrontmatterEnd + 3).trim();
  }
  adminBody = adminBody
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    .split('\n\n')
    .map((block) => {
      block = block.trim();
      if (!block) return '';
      if (block.startsWith('<h') || block.startsWith('<blockquote') || block.startsWith('<div')) return block;
      return '<p>' + block + '</p>';
    })
    .filter((b) => b)
    .join('\n\n');

  try {
    await t.sendMail({
      from: `"Content Bot" <${process.env.GMAIL_USER}>`,
      to,
      subject: `📝 New Article: ${title}`,
      html: htmlEmail,
      attachments: [
        {
          filename: `${slug || 'article'}.html`,
          content: adminBody,
          contentType: 'text/html',
        },
      ],
    });
    console.log(`  Email sent to ${to} (with HTML attachment)`);
  } catch (err) {
    console.warn(`  Warning: Failed to send email: ${err.message}`);
  }
}

export async function sendSummaryEmail(stats) {
  const t = getTransporter();
  if (!t) return;

  const to = process.env.NOTIFICATION_EMAIL;
  if (!to) return;

  if (stats.generated === 0) return; // Don't email if nothing was generated

  try {
    await t.sendMail({
      from: `"Content Bot" <${process.env.GMAIL_USER}>`,
      to,
      subject: `Content Pipeline: ${stats.generated} new article(s) ready`,
      html: `
        <p>The content pipeline just ran and generated <strong>${stats.generated} new article(s)</strong>.</p>
        <p>Checked ${stats.processed} articles from ${stats.feeds} feeds.<br>
        ${stats.relevant} were relevant, grouped into ${stats.topics} topic(s).</p>
        <p>Check your inbox for the individual articles.</p>
        <p style="color:#888;font-size:12px;">Content Pipeline</p>
      `,
    });
  } catch (err) {
    console.warn(`  Warning: Failed to send summary email: ${err.message}`);
  }
}
